- hosts: appB
  become: true
  tasks:
    - name: Installing necessary packages
      yum:
        name: epel-release
        state: latest
        disable_gpg_check: yes

    - yum:
        name: "{{item}}"
        state: latest
      with_items:
          - python-pip
          - python-devel

    - yum:
        name: "@Development tools"
        state: present

    - name: Sending requisits file
      template:
        src: templates/requerimientos.txt.j2
        dest: requerimientos.txt

    - name: Installing pre-requisits for Django
      pip:
        requirements: /home/centos/requerimientos.txt
        virtualenv_python: python2.7

    - name: Configuring gunicorn service
      template:
        src: templates/gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service
        force: yes
      notify:
          - "reload daemon"

    - name: Sendind app files
      copy:
        src: files/Back/utec
        dest: Back

    - name: Creating html folder
      file:
        path: html
        state: directory

    - template:
        src: templates/index.html.j2
        dest: html/index.html

    - name: Make data base migration 
      shell: python manage.py makemigrations web
      args:
        chdir: Back/utec

    - name: Migrating database
      shell: python manage.py migrate
      args:
        chdir: Back/utec

    - name: Intalling nginx
      yum:
        name: nginx
        state: latest

    - name: Configuring nginx
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        force: yes

    - template:
        src: templates/utec.conf.j2
        dest: /etc/nginx/conf.d/utec.conf
        force: yes
      notify:
        - "start gunicorn"
        - "restart nginx"

    - name: Change the httpd_t domain to permissive
      selinux_permissive:
        name: httpd_t
        permissive: true
  handlers:
    - name: reload daemon
      systemd:
        daemon_reload: yes
      listen: "reload daemon"

    - name: restart nginx
      systemd:
        name: nginx 
        state: restarted
      listen: "restart nginx"

    - name: start gunicorn
      systemd:
        name: gunicorn
        state: started
      listen: "start gunicorn"